export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const DISPLAY_ALERT_DUPLICATE_EMAIL = 'DISPLAY_ALERT_DUPLICATE_EMAIL'
export const DISPLAY_ALERT_EMAIL = 'DISPLAY_ALERT_EMAIL'
export const DISPLAY_ALERT_BLANK = 'DISPLAY_ALERT_BLANK'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_PLAYER_BEGIN = 'CREATE_PLAYER_BEGIN'
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS'
export const CREATE_PLAYER_ERROR = 'CREATE_PLAYER_ERROR'

export const GET_PLAYERS_BEGIN = 'GET_PLAYERS_BEGIN'
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS'

export const GET_BLOGS_BEGIN = 'GET_BLOGS_BEGIN'
export const GET_BLOGS_SUCCESS = 'GET_BLOGS_SUCCESS'

export const GET_BLOG_BEGIN = 'GET_BLOG_BEGIN'
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS'


export const SET_EDIT_PLAYER = 'SET_EDIT_PLAYER'
export const RESET_EDIT_PLAYER = 'RESET_EDIT_PLAYER'

export const SET_BLOG_PLAYER = 'SET_BLOG_PLAYER'
export const RESET_BLOG_PLAYER = 'RESET_BLOG_PLAYER'

export const DELETE_PLAYER_BEGIN = 'DELETE_PLAYER_BEGIN'

export const EDIT_PLAYER_BEGIN = 'EDIT_PLAYER_BEGIN'
export const EDIT_PLAYER_SUCCESS = 'EDIT_PLAYER_SUCCESS'
export const EDIT_PLAYER_ERROR = 'EDIT_PLAYER_ERROR'
 
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
 


/*  ------------TEAMTRAINING------------ */


export const CREATE_TEAMTRAINING_BEGIN = 'CREATE_TEAMTRAINING_BEGIN'
export const CREATE_TEAMTRAINING_SUCCESS = 'CREATE_TEAMTRAINING_SUCCESS'
export const CREATE_TEAMTRAINING_ERROR = 'CREATE_TEAMTRAINING_ERROR'


export const CREATE_COMMENT_BEGIN = 'CREATE_COMMENT_BEGIN'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR'

export const GET_COMMENTS_BEGIN = 'GET_COMMENTS_BEGIN'
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS'


export const SET_EDIT_COMMENT = 'SET_EDIT_COMMENT'
export const RESET_EDIT_COMMENT = 'RESET_EDIT_COMMENT'

export const EDIT_COMMENT_BEGIN = 'EDIT_COMMENT_BEGIN'
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS'
export const EDIT_COMMENT_ERROR = 'EDIT_COMMENT_ERROR'